### ISSUE TITLE
(Possibly) missing 'normal' escape sequence at end

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/cmder-powerline-prompt#1]
There is something wrong with how the colours of the lambda symbol are handled. See below:

![Screenshot 2020-12-31 121506](https://user-images.githubusercontent.com/46838874/103398292-11a77f00-4b62-11eb-8acc-6de935392ca6.png)

![Screenshot 2020-12-31 120823](https://user-images.githubusercontent.com/46838874/103398343-4e737600-4b62-11eb-87f0-67285bf08f51.png)

When I type something and press backspace, then a complete black line appears. This happens irrespective of whether Clink terminal.emulation is set to auto or native.

**Comment by chrisant996** [comment]
Thanks for reporting it.

The black background of the final segment triangle terminator and of the lambda symbol are issues in cmder-powerline-prompt. I've addressed those as a side effect of making the colors more easily configurable (d31c0fece57fb26dcd12bc251dabbcbc0a1820e3).

However, the "missing 'normal' escape sequence" reported in this issue is not an issue with cmder-powerline-prompt, it's an issue with Clink itself.  I've addressed it separately.

**Comment by rashil2000** [comment]
@chrisant996 Would it be possible to add custom colour config to the battery segment too (similar to date, prompt and lambda config)?

**Comment by chrisant996** [comment]
It isn't clear what you have in mind. The answer to the literal question is of course "yes", but I don't think it's the intended question.

I made the color based on the battery level. I don't know if you're asking to make the level colors configurable, to make a single static color, to add more levels, to make it possible to use 256 colors or 24-bit colors, or some other possibilities.

I'm happy to take a facilitator/moderator role for this set of scripts. I don't plan to add features for other people. I want others to feel welcome to contribute changes. All I've done here is fix various issues and add some things specifically to demonstrate some things that can be done with Clink. E.g. adding a battery status API in Clink, and showing how to use it.

**Comment by rashil2000** [comment]
Hey, extremely sorry for not making myself clear! English isn't my first language and it leads up to confusion sometimes 😅. 

I asked that because I myself was trying to mess around with some of the scripts. Since the colour was already changing according to the level, I wanted to be a bit sure if this was technically possible, because I wanted to send a PR myself. 

Please don't take it in a negative way, I didn't mean to request that feature in any way.

**Comment by chrisant996** [comment]
> Since the colour was already changing according to the level, I wanted to be a bit sure if this was technically possible, because I wanted to send a PR myself.

Oh, yes, it's possible.
You could add a `plc_` variable to control whether the battery segment uses static colors or dynamic colors.
Or you could add `plc_` variables for the battery segment text vs fill colors, but leave them nil by default, and then when actually applying the color check whether the battery segment text/fill color variables are set -- if yes then use the specified colors, and if no then use dynamic level coloring.

**Comment by rashil2000** [comment]
The second one seems like a good idea. I'll see if I can come up with something.
