### ISSUE TITLE
NPM prompt broken in latest commit

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/cmder-powerline-prompt#2]
I think the commit 6f4efbb4d02e197f7770e09270e2b89c012835bf introduced some issue in the npm segment. When cd'ing into a nodejs app directory, this is the error I get:
```

prompt filter failed:
...dhi\clink-powerline-prompt\powerline_npm.lua:39: attempt to index field 'isNeeded' (a boolean value)
stack traceback:
        ...dhi\clink-powerline-prompt\powerline_npm.lua:39: in function 'init'
        ...dhi\clink-powerline-prompt\powerline_npm.lua:84: in function 'filter'
        ?: in function <?:22>
        [C]: in function 'xpcall'
        ?: in function <?:12>
```

**Comment by chrisant996** [comment]
I fixed a bug where the code was looking in incorrect paths, and kept going an extra iteration after it needed to stop.  In most of the scripts the fix worked.  In this file, it exposed an additional latent bug.  I don't have any nodejs apps yet, so verifying the fix takes some extra time/effort.  Will try to publish a fix in the next couple of days.
