### ISSUE TITLE
Git smart prompt not working

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/cmder-powerline-prompt#3]
![image](https://user-images.githubusercontent.com/46838874/104833137-7ed64680-58bc-11eb-8da7-b7e4408caf18.png)

Like the previous NPM regression, I think there's an issue with git smart folder name too.

**Comment by chrisant996** [comment]
Yeah, thanks for reporting that.  Using `\` instead of `/` when joining path components broke a `gsub(..., "/.git")` call.  Fixed.
