### ISSUE TITLE
Scoop installer needed

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/cmder-powerline-prompt#4]
Hi! 
Could you create releases for this repository?
It'll become easier to install/update with package managers then.

**Edit:**
I got this idea because clink-completions also has a simple [releases](https://github.com/vladimir-kotikov/clink-completions/releases) page.

**Comment by chrisant996** [comment]
I understand the motivation, and it makes sense.

The "releases" from clink-completions are just a zip file containing the entire source code -- they contain things that should not really be installed onto users' computers.

How will package managers know where to install the lua scripts to, so that Clink will find them?

This suggestion has a bunch of homework that needs to be done first to figure out how it could be done.  This is not just a couple of clicks.

I'm willing to start publishing releases, if someone else can contribute the work of defining:
- What a release actually is.
- How to build a release (maybe it's a script to zip up certain files).
- Which package managers are being targeted (and also think ahead to what other package managers may need).
- How to integrate releases from here with the various package managers.

**Comment by rashil2000** [comment]
Hi!

Yes, I can give some details. 
So [this](https://github.com/vladimir-kotikov/clink-completions/issues/48) issue outlines how clink-completions is installed and used. The author recommends cloning the repository and adding its location to `clink.path`.
Now, package managers like Scoop have a feature that can suggest post-install actions to users, at install time. For example, when you install VSCode, Scoop tells you *Please run install-vscode-context.reg from ~/scoop/apps/vscode/current to enable context menu integration.* These post-install actions are defined in the scoop manifests itself.

While creating a Scoop manifest for cmder-powerline-prompt, I can simply suggest the post-install action *Please run `clink set clink.path %USERPROFILE%\scoop\apps\cmder-powerline-prompt\current\`.*

**Comment by rashil2000** [comment]
The Scoop manifest for clink-completions can be found here https://github.com/naderi/scoop-bucket/blob/master/bucket/clink-completions.json

**Comment by chrisant996** [comment]
> So [this](https://github.com/vladimir-kotikov/clink-completions/issues/48) issue outlines how clink-completions is installed and used. The author recommends cloning the repository and adding its location to `clink.path`.

One should not be required to clone a git repo simply to install a handful of scripts.

> While creating a Scoop manifest for cmder-powerline-prompt, I can simply suggest the post-install action *Please run `clink set clink.path %USERPROFILE%\scoop\apps\cmder-powerline-prompt\current\`.* 

That doesn't really work, though, in the big picture. Imagine if two projects do that. Or imagine if a user has already configured `clink.path` to something -- don't you think it would upset a user for this project to overwrite their configuration, and to cause other installed projects to stop working?

Like I said, the idea is good, but to do it right (or even merely non-destructively) takes more effort and time.

The suggestion so far is not a viable solution.

**Comment by rashil2000** [comment]
>Or imagine if a user has already configured clink.path to something -- don't you think it would upset a user for this project to overwrite their configuration, and to cause other installed projects to stop working?

I agree, it will overwrite. But I think the users of stuff like this aren't exactly laypersons, most of the time they can adapt this to suit them. The similar case would also arise in VSCode's case; it might cause duplicate or conflicting context menu entries for similar VSCode versions. 

I agree that simply running that command won't help; it needs to *append* to the clink path, something like `setx /M PATH "%PATH%;C:\some\new\path"`, but I can't think of a one-liner in this case.

One suggestion is to include a short and simple .bat file in this repo, that we can ask the users to run. That would take care of everything.

**Comment by chrisant996** [comment]
To be clear:

I'm not saying I need ideas to get me started. 

I am saying it's not something I'm going to invest my time on in the near future. I would be happy to review a pull request that contributes a working solution.

**Comment by rashil2000** [comment]
I can willingly send a PR for the .bat file.

I was not asking/suggesting to make changes; I was just contributing to the discussion. I opened the issue just to ask for making releases, which can be as simple as including the source code in them. If a repo contains only the relevant scripts, I don't think there will be any need to cut down on files to make a special release.

**Comment by rashil2000** [comment]
I came up with this extra line before the `clink set` command, that I can send in the PR

```batch
for /f "tokens=1,*" %a in ('clink set clink.path ^| findstr Value:') do (set curr=%b)
clink set clink.path %curr%;%UserProfile%\scoop\apps\cmder-powerline-prompt\current\
```

**Comment by chrisant996** [comment]
> If a repo contains only the relevant scripts, I don't think there will be any need to cut down on files to make a special release.

This repo contains more than just the relevant scripts. It contains .gitignore, screenshots for the readme.md, and a docs folder with old documentation for reference purposes while script developers work on the scripts (the docs are not relevant or suitable for consumption by end users).

**Comment by chrisant996** [comment]
I deleted the docs\ directory and the supporting documentation in it.
I published a release.
I'm not sure I understand how that by itself will be useful, but hopefully it is!

**Comment by rashil2000** [comment]
Thanks! 

I will send you the link to scoop manifest (with install instructions in it) once it gets merged.

**Comment by rashil2000** [comment]
Here's the link https://github.com/naderi/scoop-bucket/blob/master/bucket/cmder-powerline-prompt.json

**Comment by naderi** [comment]
Hi @rashil2000,
The Update function in the scoop script doesn't work because for GitHub standard update procedures in scoop, the version must be started with "v." or "V." and not with "rel." like yours.

**Comment by chrisant996** [comment]
Ok, I renamed the release to "v.1bf5ea".  The project has never had a version number before, and I don't want to be forced at this time to create a version numbering system (or choose where to start it).  I trust that commit hashes can be accepted as version numbers by scoop (i.e. "v._short_hash_").

**Comment by naderi** [comment]
Hi @chrisant996,
Thank you for update, but unfortunately it still doesn't work, because a valid version from scoop point of view contains only numbers and points. I have now changed the manifest so that it works even with values like rel.1a2b3c. You can undo the changes if you want.

**Comment by chrisant996** [comment]
@rashil2000 I added `clink installscripts` and `clink uninstallscripts` to make it easy for package managers like Scoop to be able to install scripts and tell Clink about them.

I would encourage replacing the copy/paste cmd commands with the manifest actually invoking `clink installscripts <pkg_dir>`.

**Comment by rashil2000** [comment]
naderi/scoop-bucket#6

**Comment by chrisant996** [comment]
@rashil2000 why not use a scoop `post_install` command? Why make the user have to do manual steps?

**Comment by rashil2000** [comment]
Because we cannot assume that the user has clink installed. He might be using the scripts for cmder, for example.

post_install is not for running programs/apps, I think it's there for running PowerShell commands to do cleanup, create config directories, move folders etc.

**Comment by chrisant996** [comment]
> Because we cannot assume that the user has clink installed. He might be using the scripts for cmder, for example.

Cmder has the scripts built in. Using scoop to install the scripts is not really compatible with Cmder in the first place: it would cause the scripts to load and run _twice_ for everything.

So installing this via scoop should _only_ be done if Clink is installed.

The instructions for this manifest seem to currently tell users to unconditionally run the clink installscripts command. If the reason it's not done automatically is that it's believed to be wrong in some cases, then the text needs to document that. Otherwise users would follow the steps and cause problems for themselves. But since installing this at all with scoop is incompatible with Cmder, there should probably be documentation about that, and maybe even an automated validation guard to help users not get themselves into a bad state.

> post_install is not for running programs/apps, I think it's there for running PowerShell commands to do cleanup, create config directories, move folders etc. 

Why do you think that?

Look at the example in the `post_install` documentation, which invokes a .exe file via post_install.

Also, scripts are programs... 😉

**Comment by rashil2000** [comment]
> Why do you think that?

I say this because I have seen hundreds of manifests till date (even sent some PRs), and I haven't encountered any post_install field invoking executables. Of course it might have been an oversight, I'm not denying that. 

Most manifests usually suggest users to do the initial setup. Like take the example of msys2, it suggests running 'Run {some_command} to finish the initialization'. Of course scoop could have run that itself too, but this is just what I've seen. 

In case of clink, we also cannot assume the user has clink in his PATH. They might be invoking aliases for clink, or running it directly from the Start menu.

**Comment by rashil2000** [comment]
> Cmder has the scripts built in. 

I was not aware of this. Does cmder-powerline-prompt get installed automatically when I install cmder? I don't recall it doing that.

**Comment by chrisant996** [comment]
> > Cmder has the scripts built in.
> 
> I was not aware of this. Does cmder-powerline-prompt get installed automatically when I install cmder? I don't recall it doing that.

Ah, oops.  I must have confused clink-completions and cmder-powerline-prompt.

Since you're right, cmder-powerline-prompt is _not_ built into Cmder, that means it's a perfect candidate for `clink installscripts`:

1. A `post_install` script can check if Clink is installed via Scoop, or via the Clink EXE installer in its default location, or via Cmder in its default location.
2. If Clink is found, then the `post_install` script can invoke `clink installscripts`, and _all_ installed copies of a recent-enough Clink will use the cmder-powerline-prompt scripts, regardless how or where they're installed (the script can also check whether any of the Clink's are new enough to support the installscripts command).
3. But if not found, then the `post_install` script can either do nothing, or can print an instructional message saying how else it can be hooked up.

Let's zoom out for a moment:

My big picture feedback is that the user experience is not very smooth the way the manifest is currently set up.  The instructions in the repo's readme were clear and reasonable.  It's true they weren't automatic.  The scoop manifest is trying to make it "install" the scripts.  But the manifest is still not automatic, it gives instructions that don't always work, and they disagree with the instructions in the repo.  Doesn't that seem both confusing and also not a real "install" experience from a user's perspective?

**Comment by rashil2000** [comment]
The steps that you mention will make the manifest extremely complicated, I'm not sure if that kind of error-checking functionality is even supported by the post_install. Picture this for instance: since the user is already using Scoop, what if he installed cmder through scoop itself? Then that first step would need another condition check inside 'scoop/apps/cmder' directory.

The peculiar thing about scoop is that it's not a traditional package manager, in the strictest sense. Package management is more of a Unix concept, and I think there's only one true actual package manager that seems to replicate that on Windows - Chocolatey - which builds and maintains binaries in its own servers. Scoop is more of a fetch-this-zip-and-extract-it-for-the-user. 

>it gives instructions that don't always work

Could you elaborate more on this? The suggestion just asks the user to run a command. If the user knows what this repo does, he'll very well know what Clink is and whether Clink is there in his PATH and run that himself. I don't see how it's failing. I'm just saying pre-meditating everything in the manifest itself is making some assumptions for which there's no need. 

Let me illustrate it like this: I'm a user of Clink, but I don't use cmder. Now how do I manage clink-completions? I install it (or rather, download and extract it) using Scoop, and although clink-completions' manifest gives no instructions whatsoever, I still know that I just need to set the folder in Clink's script path. This is just an example.

**Comment by chrisant996** [comment]
> Let me illustrate it like this: I'm a user of Clink, but I don't use cmder. Now how do I manage clink-completions? I install it (or rather, download and extract it) using Scoop, and although clink-completions' manifest gives no instructions whatsoever, I still know that I just need to set the folder in Clink's script path. This is just an example.

First, that's just one way that some users may respond.  Another way is they may copy the files directly into their already-existing Clink script folder where they're collecting all their favorite Clink scripts.

**But I wonder if you've missed an important detail:**  Setting `clink.path` _changes how Clink works_.  When `clink.path` is empty (the default), scripts are loaded from two preset places by default.  As soon as you set any value in `clink.path` _those preset places are no longer used to load scripts_.  (This is pre-existing behavior that I have preserved for compatibility with v0.4.9 and earlier.)

The instructions you've given and the approach you've suggested is how users "will just know" to do are not benign.  They can actually be destructive to a user's existing configuration, and they are not the expected way of using Clink.

> The steps that you mention will make the manifest extremely complicated, I'm not sure if that kind of error-checking functionality is even supported by the post_install.

It's really not that complicated.  And certainly post_install can handle that: post_install simply runs anything, so the question isn't whether post_install can do it, the question is about whether to write the code.

> Picture this for instance: since the user is already using Scoop, what if he installed cmder through scoop itself? Then that first step would need another condition check inside 'scoop/apps/cmder' directory.

I agree that particular approach seems complicated.  I would encourage a simpler approach.  For example, what if `where clink` and `where cmder` were used to detect if Clink or Cmder is present in the PATH?  This doesn't need to be big or complicated.

> The peculiar thing about scoop is that it's not a traditional package manager, in the strictest sense. Package management is more of a Unix concept, and I think there's only one true actual package manager that seems to replicate that on Windows - Chocolatey - which builds and maintains binaries in its own servers. Scoop is more of a fetch-this-zip-and-extract-it-for-the-user.

Scoop has a bunch of support for doing installation steps.  I don't think Scoop's intent is as limited as you suggest.  I've only installed a few things with Scoop, but they all have run installation steps and produced a state where the effect is that the thing has been "installed" and "just works" -- no extra manual steps needed, and definitely not merely extracting.

I feel this does not showcase Scoop's capabilities, and does not showcase Clink's capabilities.  I don't want to produce "releases" for cmder-powerline-prompt if scoop is going to be merely a different spelling of "git clone".  Scoop is capable of actual installs.  I had agreed to produce releases (and added features in Clink itself) with the intent of actually installing the scripts.

**Comment by chrisant996** [comment]
> Now, package managers like Scoop have a feature that can suggest post-install actions to users, at install time. For example, when you install VSCode, Scoop tells you _Please run install-vscode-context.reg from ~/scoop/apps/vscode/current to enable context menu integration._ These post-install actions are defined in the scoop manifests itself.

But that's an _optional_ step.  Without that step, context menu integration isn't enabled -- but VSCode is still installed and works.

**Comment by rashil2000** [comment]
> I had agreed to produce releases (and added features in Clink itself) with the intent of actually installing the scripts.

Sure, if that's the case, I can readily add a post_install to manifest. But I can't come up with a a couple of statements to add, that are both succinct and to the point (which don't make the manifest too clunky). So I'll definitely need suggestions here.

**Comment by chrisant996** [comment]
> > I had agreed to produce releases (and added features in Clink itself) with the intent of actually installing the scripts.
> 
> Sure, if that's the case, I can readily add a post_install to manifest. But I can't come up with a a couple of statements to add, that are both succinct and to the point (which don't make the manifest too clunky). So I'll definitely need suggestions here.

I'm focused on other things right now.  I'll offer some suggestions when I get a chance.

In retrospect, I shouldn't have generated a release yet for this repo, until there was a plan in place for how to write the installer.  This was exactly the stuff I called out initially as needing more investment to do a good job.  I didn't realize how far apart our understandings were on the topic.  That's my mistake.

Please understand in the future, if I push back and decline something, citing that it's going to involve more work than has been noted yet.

**Comment by rashil2000** [comment]
I have created the installer and uninstaller - the PR is naderi/scoop-bucket#9

It checks for the clink executable, then the CMDER_ROOT environment variable, and fails with a message if neither are found.

**Comment by rashil2000** [comment]
Can this issue be closed now?

**Comment by chrisant996** [comment]
> Can this issue be closed now? 

Feel free.  It seems appropriate that whoever finishes a work item will be the one to close the work item. 👍

Thanks for contributing!

**Comment by rashil2000** [comment]
Okay, thanks! 
Be sure to follow the current scheme of commit hashes in future release names so that scoop updaters can pick it up.

**Comment by chrisant996** [comment]
> ... so that scoop updaters can pick it up.

That raises a question:

The next release from this repo will be very soon.
And it has introduced some breaking changes.

Is there a way in scoop to require user consent for an update?
E.g. if major version numbers automatically require consent, then maybe the version number scheme here should be changed?

Or I could try to add backward compatibility, but that gets messy.  (Especially since some bugs in the original project made configuration not work as advertised, which is what led to the breaking changes.)

**Comment by rashil2000** [comment]
> Is there a way in scoop to require user consent for an update?

According to the manifest docs, no - https://scoop-docs.now.sh/docs/concepts/App-Manifests.html

The way it works is like this - `scoop update` updates all manifests, but not the packages themselves, `scoop update <app_name>` updates a particular package unconditionally, and `scoop update *` updates all packages (for which updates are available) unconditionally.

For breaking changes, I have seen some messages in the Notes section that we can show to the user, but that is all.

**Comment by chrisant996** [comment]
Ah, ok, thanks.  That's unfortunate.  I guess I will have to throw together a compatibility layer for the project.
